### ISSUE TITLE
add more squids

### ISSUE THREAD

**Issue by Loweh** [flashwave/misuzu#70]
P L S

**Comment by flashwave** [comment]
no
![aggravated](https://user-images.githubusercontent.com/5001057/47471218-9e7b8300-d809-11e8-976e-e625b3bdf114.png)

**Comment by Loweh** [comment]
MOM PLEASE 

![](http://aroltd.com/nabucco/chat/img/emotes/sad.png)

**Comment by flashwave** [comment]
![ultreme](https://user-images.githubusercontent.com/5001057/47471282-e39fb500-d809-11e8-8822-67faca7dc80b.png)
